/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Observable,
} from 'rxjs';
import {
  languageTypes,
} from './constants';
import {
  Notifier,
  UserNotification,
} from './store/types';

export namespace Components {
  interface AntivirusWidget {
    /**
    * infected files count
    */
    'infectedCount': number;
    /**
    * global notifier object
    */
    'notifier': Notifier;
    /**
    * Site id
    */
    'siteId': number;
    /**
    * Translate service
    */
    'translateService': { currentLang: string; onLangChange: Observable<{ lang: languageTypes }> };
    /**
    * url to antivirus main page
    */
    'url': string;
    /**
    * Global user notification service
    */
    'userNotification': UserNotification;
  }
}

declare global {


  interface HTMLAntivirusWidgetElement extends Components.AntivirusWidget, HTMLStencilElement {}
  var HTMLAntivirusWidgetElement: {
    prototype: HTMLAntivirusWidgetElement;
    new (): HTMLAntivirusWidgetElement;
  };
  interface HTMLElementTagNameMap {
    'antivirus-widget': HTMLAntivirusWidgetElement;
  }
}

declare namespace LocalJSX {
  interface AntivirusWidget extends JSXBase.HTMLAttributes<HTMLAntivirusWidgetElement> {
    /**
    * infected files count
    */
    'infectedCount'?: number;
    /**
    * global notifier object
    */
    'notifier'?: Notifier;
    /**
    * Site id
    */
    'siteId'?: number;
    /**
    * Translate service
    */
    'translateService'?: { currentLang: string; onLangChange: Observable<{ lang: languageTypes }> };
    /**
    * url to antivirus main page
    */
    'url'?: string;
    /**
    * Global user notification service
    */
    'userNotification'?: UserNotification;
  }

  interface IntrinsicElements {
    'antivirus-widget': AntivirusWidget;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


