image:
  node:12-alpine

stages:
  - build

before_script:
  - cd client
  - npm install
  - npx lerna bootstrap

build:
  stage: build
  script:
    - sh scripts/build.sh
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - client/node_modules
  artifacts:
    expire_in: 3 mos
    paths:
      - build/
