# vim: tabstop=2:softtabstop=2:shiftwidth=2:expandtab
version: "3.5"

services:
  plugin:
    image: gitlab-dev.ispsystem.net:5005/ispsystem/plugin/service:master
    container_name: plugin
    environment:
      MYSQL_DATABASE: auth
      MYSQL_PASSWORD: 6zGC7qSEyK
      MYSQL_USER: root
      KV_STORAGE_ADDR: consul
      PROXY_SERVICE: input:1500
      LOG_SETTINGS_FILE_LEVEL: debug
    labels:
      SERVICE_80_NAME: plugin_front
      SERVICE_80_TAGS: frontend,static
      SERVICE_80_URI: /plugin/
      SERVICE_1600_NAME: plugin_v3
      SERVICE_1600_TAGS: reader,backend
      SERVICE_1601_NAME: plugin_v3
      SERVICE_1601_TAGS: writer,backend
      SERVICE_CHECK_TCP: 'true'
      SERVICE_CHECK_INTERVAL: 10s
      SERVICE_CHECK_TIMEOUT: 1s
      SERVICE_CHECK_DEREGISTER_AFTER: 60m
    #TODO(d.smirnov): Это отладочные настройки. Выпилить
#    volumes:
#      - /Users/d.smirnov/development/repo/service/build/dist/opt/ispsystem/plugin_service/bin:/opt/ispsystem/plugin_service/bin
#      - /Users/d.smirnov/development/repo/service/build/dist/opt/ispsystem/plugin_service/lib:/opt/ispsystem/plugin_service/lib
#      - /Users/d.smirnov/development/repo/service/etc:/opt/ispsystem/plugin_service/etc
#      - /Users/d.smirnov/development/repo/service/supervisord.conf.d:/etc/supervisord.conf.d

networks:
  default:
    external:
      name: auth