/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AntivirusWidget {
    'url': string;
  }
}

declare global {


  interface HTMLAntivirusWidgetElement extends Components.AntivirusWidget, HTMLStencilElement {}
  var HTMLAntivirusWidgetElement: {
    prototype: HTMLAntivirusWidgetElement;
    new (): HTMLAntivirusWidgetElement;
  };
  interface HTMLElementTagNameMap {
    'antivirus-widget': HTMLAntivirusWidgetElement;
  }
}

declare namespace LocalJSX {
  interface AntivirusWidget extends JSXBase.HTMLAttributes<HTMLAntivirusWidgetElement> {
    'url'?: string;
  }

  interface IntrinsicElements {
    'antivirus-widget': AntivirusWidget;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


