/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AntivirusMenu {
    'url': string;
  }
  interface NgispuiVmenuItem {}
}

declare global {


  interface HTMLAntivirusMenuElement extends Components.AntivirusMenu, HTMLStencilElement {}
  var HTMLAntivirusMenuElement: {
    prototype: HTMLAntivirusMenuElement;
    new (): HTMLAntivirusMenuElement;
  };

  interface HTMLNgispuiVmenuItemElement extends Components.NgispuiVmenuItem, HTMLStencilElement {}
  var HTMLNgispuiVmenuItemElement: {
    prototype: HTMLNgispuiVmenuItemElement;
    new (): HTMLNgispuiVmenuItemElement;
  };
  interface HTMLElementTagNameMap {
    'antivirus-menu': HTMLAntivirusMenuElement;
    'ngispui-vmenu-item': HTMLNgispuiVmenuItemElement;
  }
}

declare namespace LocalJSX {
  interface AntivirusMenu extends JSXBase.HTMLAttributes<HTMLAntivirusMenuElement> {
    'url'?: string;
  }
  interface NgispuiVmenuItem extends JSXBase.HTMLAttributes<HTMLNgispuiVmenuItemElement> {}

  interface IntrinsicElements {
    'antivirus-menu': AntivirusMenu;
    'ngispui-vmenu-item': NgispuiVmenuItem;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


